const List<String> professionalCategories = [
  'Ajudante',
  'Alpinista industrial',
  'Arquiteto',
  'Azulejista',
  'Bombeiro civil',
  'Bombeiro hidráulico',
  'Calheiro',
  'Carpinteiro',
  'Chaveiro',
  'Consultor técnico',
  'Dedetizador',
  'Designer de interiores',
  'Eletricista',
  'Eletricista automotivo',
  'Encanador',
  'Engenheiro civil',
  'Engenheiro eletricista',
  'Estucador',
  'Gesseiro',
  'Instalador de alarmes',
  'Instalador de antenas',
  'Instalador de câmeras',
  'Instalador de energia solar',
  'Instalador de portão automático',
  'Jardineiro',
  'Ladrilheiro',
  'Lavador de estofados',
  'Marceneiro',
  'Marmorista',
  'Mecânico',
  'Mecânico industrial',
  'Montador de móveis',
  'Operador de máquinas',
  'Pedreiro',
  'Pintor',
  'Piscineiro',
  'Projetista',
  'Serralheiro',
  'Servente',
  'Soldador',
  'Supervisor técnico',
  'Técnico de automação',
  'Técnico de CFTV',
  'Técnico de computadores',
  'Técnico de controles de acesso',
  'Técnico de elevadores',
  'Técnico de eletrodomésticos',
  'Técnico de energia solar',
  'Técnico de esquadrias',
  'Técnico de impressoras',
  'Técnico de informática',
  'Técnico de máquinas de lavar',
  'Técnico de refrigeração',
  'Técnico de segurança eletrônica',
  'Técnico de telefonia',
  'Técnico em automação predial',
  'Técnico em climatização',
  'Técnico em elétrica',
  'Técnico em hidráulica',
  'Técnico em manutenção predial',
  'Técnico em redes',
  'Vidraceiro',
];
