// Mocks generated by Mockito 5.4.6 from annotations
// in serviceflow/test/customers/customer_form_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:serviceflow/features/customers/data/customer_repository.dart'
    as _i6;
import 'package:serviceflow/features/customers/domain/customer.dart' as _i2;
import 'package:serviceflow/features/customers/domain/customer_address.dart'
    as _i4;
import 'package:serviceflow/features/customers/domain/customer_asset.dart'
    as _i5;
import 'package:serviceflow/features/customers/domain/customer_contact.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomer_0 extends _i1.SmartFake implements _i2.Customer {
  _FakeCustomer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerContact_1 extends _i1.SmartFake
    implements _i3.CustomerContact {
  _FakeCustomerContact_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerAddress_2 extends _i1.SmartFake
    implements _i4.CustomerAddress {
  _FakeCustomerAddress_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomerAsset_3 extends _i1.SmartFake implements _i5.CustomerAsset {
  _FakeCustomerAsset_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerRepository extends _i1.Mock
    implements _i6.CustomerRepository {
  MockCustomerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<({List<_i2.Customer> items, int totalCount})> listPaged({
    _i6.CustomerFilter? filter = const _i6.CustomerFilter(),
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listPaged,
          [],
          {
            #filter: filter,
            #page: page,
          },
        ),
        returnValue:
            _i7.Future<({List<_i2.Customer> items, int totalCount})>.value(
                (items: <_i2.Customer>[], totalCount: 0)),
      ) as _i7.Future<({List<_i2.Customer> items, int totalCount})>);

  @override
  _i7.Future<_i2.Customer> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i7.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.Customer>);

  @override
  _i7.Future<_i2.Customer> create(_i2.Customer? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [customer],
        ),
        returnValue: _i7.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #create,
            [customer],
          ),
        )),
      ) as _i7.Future<_i2.Customer>);

  @override
  _i7.Future<_i2.Customer> update(
    String? id,
    _i2.Customer? customer,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            customer,
          ],
        ),
        returnValue: _i7.Future<_i2.Customer>.value(_FakeCustomer_0(
          this,
          Invocation.method(
            #update,
            [
              id,
              customer,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Customer>);

  @override
  _i7.Future<void> deactivate(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> reactivate(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reactivate,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.CustomerContact>> getContacts(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [customerId],
        ),
        returnValue: _i7.Future<List<_i3.CustomerContact>>.value(
            <_i3.CustomerContact>[]),
      ) as _i7.Future<List<_i3.CustomerContact>>);

  @override
  _i7.Future<_i3.CustomerContact> addContact(_i3.CustomerContact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [contact],
        ),
        returnValue:
            _i7.Future<_i3.CustomerContact>.value(_FakeCustomerContact_1(
          this,
          Invocation.method(
            #addContact,
            [contact],
          ),
        )),
      ) as _i7.Future<_i3.CustomerContact>);

  @override
  _i7.Future<_i3.CustomerContact> updateContact(_i3.CustomerContact? contact) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContact,
          [contact],
        ),
        returnValue:
            _i7.Future<_i3.CustomerContact>.value(_FakeCustomerContact_1(
          this,
          Invocation.method(
            #updateContact,
            [contact],
          ),
        )),
      ) as _i7.Future<_i3.CustomerContact>);

  @override
  _i7.Future<void> deleteContact(String? contactId) => (super.noSuchMethod(
        Invocation.method(
          #deleteContact,
          [contactId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.CustomerAddress>> getAddresses(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddresses,
          [customerId],
        ),
        returnValue: _i7.Future<List<_i4.CustomerAddress>>.value(
            <_i4.CustomerAddress>[]),
      ) as _i7.Future<List<_i4.CustomerAddress>>);

  @override
  _i7.Future<_i4.CustomerAddress> addAddress(_i4.CustomerAddress? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAddress,
          [address],
        ),
        returnValue:
            _i7.Future<_i4.CustomerAddress>.value(_FakeCustomerAddress_2(
          this,
          Invocation.method(
            #addAddress,
            [address],
          ),
        )),
      ) as _i7.Future<_i4.CustomerAddress>);

  @override
  _i7.Future<_i4.CustomerAddress> updateAddress(_i4.CustomerAddress? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [address],
        ),
        returnValue:
            _i7.Future<_i4.CustomerAddress>.value(_FakeCustomerAddress_2(
          this,
          Invocation.method(
            #updateAddress,
            [address],
          ),
        )),
      ) as _i7.Future<_i4.CustomerAddress>);

  @override
  _i7.Future<void> deleteAddress(String? addressId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [addressId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.CustomerAsset>> getAssets(String? customerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAssets,
          [customerId],
        ),
        returnValue:
            _i7.Future<List<_i5.CustomerAsset>>.value(<_i5.CustomerAsset>[]),
      ) as _i7.Future<List<_i5.CustomerAsset>>);

  @override
  _i7.Future<_i5.CustomerAsset> addAsset(_i5.CustomerAsset? asset) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAsset,
          [asset],
        ),
        returnValue: _i7.Future<_i5.CustomerAsset>.value(_FakeCustomerAsset_3(
          this,
          Invocation.method(
            #addAsset,
            [asset],
          ),
        )),
      ) as _i7.Future<_i5.CustomerAsset>);
}
